<!--Template for Register your product on Product page view-->
<div class="relative float-none lg:float-right w-full lg:w-1/2">
    <div class="w-full mt-10 lg:mt-0 lg:w-[400px] text-left h-auto bg-[#f8f8f8] p-4 shadow-miniSearch border border-solid border-[#0000001a] rounded-[3px]">
        <h3 class="text-primary mb-3 text-base font-semibold"><?php echo __('Register Your Product') ?></h3>
        <p class="text-sm"><?php echo __('You can register your Vax product on the Vax website registrations page.') ?></p>
        <a class="btn btn-primary w-[222px] mt-4 block"
           href="https://www.vax.co.uk/registration"><?php echo __('Register your product') ?></a>
    </div>
</div>
