<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/**
 * Spares & Accessories Prducts with filter sidebar
 * @var \VaxLtd\SupportPortal\Block\Category\Products $block
 * @var ViewModelRegistry $viewModels
 * @var HeroiconsSolid $heroiconsSolid
 * @var SvgIcons $hyvaicons
 * @var HeroiconsOutline $heroicons
 */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
$hyvaicons = $viewModels->require(SvgIcons::class);
$selectedProduct = $block->getCurrentProduct();

$relatedCollection = $block->getRelatedProductsPaged($selectedProduct);
$resultSize = $this->getResultSize();
$pageSize = $block->getPageSize();
$nextPageUrl = $block->getNextPageUrl();

$cartHelper = $this->helper('VaxLtd\Checkout\Helper\Cart');
$productHelper = $this->helper('VaxLtd\Catalog\Helper\Product');
$image = 'related_products_list';
$title = __('Spares &amp; Accessories');

?>

<div class="mt-10 pb-10">
    <h3 class="lg:hidden text-primary text-center text-[24px] font-semibold tracking-[-0.2px]">
        <?= $title; ?>
    </h3>
    <!--    List products for Spares    -->
    <div>
        <h3
                class="hidden lg:block mb-5 text-primary text-center text-[24px] font-semibold tracking-[-0.2px]">
            <?= $title; ?>
        </h3>
        <div
                class="mb-4 pb-2 text-sm text-center lg:text-left text-darkgrayish font-semibold lg:border-b border-solid border-[#0000001a]">
            <?= $resultSize; ?> Result(s) for
            "<?= $selectedProduct->getName(); ?>"
        </div>
        <?php if ($relatedCollection) : ?>
            <div class="mb-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-4"
                 id="product-list">
                <?php foreach ($relatedCollection as $_item) : ?>
                    <?php $productUrl = $block->getProductUrlByDefaultStore($_item) ?>

                    <form method="POST"
                          action="<?= $cartHelper->getAddToCartUrl($productHelper->getProductModel($_item->getId())) ?>"
                          class="relative grid grid-rows-[max-height,auto] p-4 bg-white box-border shadow-miniSearch border border-solid border-[#e9eaee]">
                        <a href="<?= $productUrl ?>">
                            <?= $block->getImage($_item, $image)->toHtml(); ?>
                        </a>
                        <div class="grid grid-rows-[70px,auto,1fr]">
                            <a class="block pt-2 pb-4 overflow-hidden text-primary text-sm font-medium"
                               title="<?= $block->escapeHtml($_item->getName()) ?>"
                               href="<?= $productUrl ?>">
                                <?= $block->escapeHtml($_item->getName()) ?>
                            </a>
                            <div class="product-price block py-3 text-primary text-base font-bold">
                                <?= $block->getProductPrice($_item); ?>
                            </div>
                            <div class="mt-auto">
                            <?php echo $block->getBlockHtml('formkey')?>
                                <div class="actions-primary">
                                    <?php if ($_item->isAvailable()) : ?>
                                        <button class="btn btn-orange w-full"
                                                type="submit"
                                                title="<?= __('Add to Cart') ?>">
                                            <?= $hyvaicons->shoppingCartRegularHtml('mr-1', 19, 17) ?>
                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php elseif ($_item->isDiscontinued()) : ?>
                                        <button type="button"
                                                class="btn bg-[#e0e0e0] hover:bg-[#e0e0e0] w-full text-sm leading-6 text-darkgrayish italic font-semibold cursor-default">
                                            <span><?= __('Product Discont.') ?></span>
                                        </button>
                                    <?php else : ?>
                                        <button type="button"
                                                class="btn bg-[#e0e0e0] hover:bg-[#e0e0e0] w-full text-sm leading-6 text-darkgrayish italic font-semibold cursor-default">
                                            <span><?= __('Out of stock') ?></span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </form>
                <?php endforeach ?>
            </div>
        <?php if ($nextPageUrl) : ?>
            <script type="application/json"
                    id="nextPageUrl">
                {
                    "nextPageUrl": "<?= $nextPageUrl ?>"
            }
            </script>
        <?php endif ?>
        <?php if ($resultSize > $pageSize) : ?>
            <script>
                document.addEventListener('alpine:init', () => {
                    Alpine.data('infiniteScroll', () => ({
                        nextPageUrl: '<?= $nextPageUrl ?>',
                        isLoading: false,
                        loadMore() {
                            this.isLoading = true;

                            fetch(this.nextPageUrl)
                                .then(res => res.text())
                                .then(rawHtml => {
                                    const parser = new DOMParser();

                                    const html = parser.parseFromString(rawHtml, "text/html");
                                    const container = document.getElementById('product-list');

                                    const list = html.getElementById('product-list');
                                    container.append(...list.children);

                                    const nextPageUrl = html.getElementById('nextPageUrl');
                                    if (nextPageUrl) this.nextPageUrl = JSON.parse(nextPageUrl.textContent).nextPageUrl;
                                    else this.nextPageUrl = null;
                                })
                                .finally(() => this.isLoading = false)
                        }
                    }))
                })
            </script>

            <style>
                @keyframes reveal {
                    from {
                        transform: scale(0.001);
                    }

                    to {
                        transform: scale(1);
                    }
                }

                @keyframes slide {
                    to {
                        transform: translateX(30px);
                    }
                }

                #loadingIcon div {
                    animation-duration: 0.5s;
                    animation-timing-function: ease;
                    animation-iteration-count: infinite;
                }

                #loadingIcon div:nth-child(1) {
                    animation-name: reveal;
                }

                #loadingIcon div:nth-child(2),
                #loadingIcon div:nth-child(3) {
                    animation-name: slide;
                }

                #loadingIcon div:nth-child(4) {
                    animation-name: reveal;
                    animation-direction: reverse;
                }
            </style>

            <div x-data="infiniteScroll">
                <template x-if="isLoading">
                    <div id="loadingIcon"
                         class="relative w-20 mx-auto h-5 mb-3">
                        <div class="absolute left-0 w-5 h-5 rounded-full bg-[#555]"></div>
                        <div class="absolute left-0 w-5 h-5 rounded-full bg-[#555]"></div>
                        <div class="absolute left-[30px] w-5 h-5 rounded-full bg-[#555]"></div>
                        <div class="absolute left-[60px] w-5 h-5 rounded-full bg-[#555]"></div>
                    </div>
                </template>
                <template x-if="nextPageUrl">
                    <div class="mx-auto text-center">
                        <button type="button"
                                class="btn btn-primary"
                                :disabled="isLoading"
                                @click="loadMore()"><?= __('Load more') ?></button>
                    </div>
                </template>
            </div>
        <?php endif ?>
        <?php endif ?>
    </div>
</div>
